/**
 * MPI AI Capability Registry & Modular Orchestration Architecture
 *
 * Implements the official 62-capability blueprint across 6 core pillars:
 * 1. Demand capture and procurement intake
 * 2. Supplier discovery and MSME enablement
 * 3. RFQ, quotation and commercial comparison
 * 4. Schemes, compliance and business navigation
 * 5. Analytics, forecasting, risk and performance
 * 6. Copilots, workflow and trust
 *
 * Architectural Principle:
 * Separates existing working AI capabilities (available/beta) from future roadmap capabilities (planned).
 * Ensures deterministic structured output, calibrated confidence ratings, and strict human authorization gates.
 */

export type AICapabilityCategory =
  | "demand_capture"
  | "supplier_discovery"
  | "rfq_quotation"
  | "schemes_compliance"
  | "analytics_forecasting"
  | "copilots_trust"

export type AICapabilityStatus = "available" | "beta" | "prototype" | "planned" | "deprecated"

export type UserRole = "public" | "startup" | "msme" | "admin"

export type EvidenceSourceType = "verified_data" | "supplier_declared" | "estimated" | "ai_inference"

export interface AIEvidenceItem {
  factor: string
  type: EvidenceSourceType
  description: string
}

export interface AIConfidenceRating {
  score: number // 0.0 to 1.0
  level: "High confidence" | "Needs confirmation" | "Insufficient evidence"
  explanation?: string
}

export interface AINextAction {
  action: string
  label: string
  targetScreen?: string
  payload?: Record<string, unknown>
}

/**
 * Mandatory Structured Output Contract (Section 5)
 */
export interface AIStandardOutput<T = unknown> {
  status: "success" | "partial" | "needs_input" | "failed"
  result: T
  confidence: AIConfidenceRating
  missing_information: string[]
  evidence: AIEvidenceItem[]
  warnings: string[]
  next_action?: AINextAction
}

export interface AICapabilityDefinition {
  id: string
  name: string
  category: AICapabilityCategory
  description: string
  status: AICapabilityStatus
  isImplemented: boolean
  confidenceSupported: boolean
  requiredRole: UserRole[]
  requiresHumanApproval: boolean
  inputSchema: Record<string, string>
  outputSchema: Record<string, string>
  toolsRequired: string[]
}

/**
 * Canonical 62-Capability Registry
 */
export const MPI_AI_CAPABILITIES: Record<string, AICapabilityDefinition> = {
  // ─── 1. DEMAND CAPTURE & INTAKE (1–10) ────────────────────────────────────
  demand_intake_parser: {
    id: "demand_intake_parser",
    name: "Natural Language Requirement Parser",
    category: "demand_capture",
    description: "Transforms conversational English into structured engineering bills of materials (BOM), units, tolerances, and constraints.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup"],
    requiresHumanApproval: false,
    inputSchema: { requirementText: "string", userRole: "string?" },
    outputSchema: { category: "string", materialGrade: "string", batchQuantity: "number", budgetEstimate: "number", confidence: "object" },
    toolsRequired: ["gemini_generate_content", "taxonomy_matcher"],
  },
  guided_clarification_engine: {
    id: "guided_clarification_engine",
    name: "Interactive Clarification Assistant",
    category: "demand_capture",
    description: "Generates progressive non-redundant questions when required manufacturing specifications are missing or ambiguous.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup"],
    requiresHumanApproval: false,
    inputSchema: { partialRequirement: "string", missingFields: "string[]" },
    outputSchema: { questions: "string[]", guidance: "string" },
    toolsRequired: ["gemini_generate_content"],
  },
  demand_classification: {
    id: "demand_classification",
    name: "Taxonomy & Category Classifier",
    category: "demand_capture",
    description: "Maps user intents against MPI's 7 official procurement verticals and 50+ subcategories.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup"],
    requiresHumanApproval: false,
    inputSchema: { prompt: "string" },
    outputSchema: { primaryCategory: "string", secondaryCategories: "string[]" },
    toolsRequired: ["taxonomy_matcher"],
  },
  need_to_catalogue_mapping: {
    id: "need_to_catalogue_mapping",
    name: "Catalogue Taxonomy Mapper",
    category: "demand_capture",
    description: "Identifies matching standardized catalogue items for customized or generic demand requests.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup"],
    requiresHumanApproval: false,
    inputSchema: { query: "string", category: "string" },
    outputSchema: { matchedProductIds: "string[]", similarityScores: "number[]" },
    toolsRequired: ["mpi_catalog_index"],
  },
  spec_completeness_auditor: {
    id: "spec_completeness_auditor",
    name: "Specification Completeness Auditor",
    category: "demand_capture",
    description: "Scores RFQ technical readiness and highlights manufacturing constraints needed for machine tooling.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { rfqSpecs: "object" },
    outputSchema: { readinessScore: "number", missingParameters: "string[]" },
    toolsRequired: ["specification_rules_engine"],
  },
  specification_drafting_copilot: {
    id: "specification_drafting_copilot",
    name: "CAD & Technical Spec Drafting Copilot",
    category: "demand_capture",
    description: "Drafts comprehensive manufacturing job-sheets with ISO/DIN tolerance standards.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: true,
    inputSchema: { specs: "object", tolerances: "string" },
    outputSchema: { technicalDossier: "string", checklist: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  contradiction_detector: {
    id: "contradiction_detector",
    name: "Engineering Contradiction Detector",
    category: "demand_capture",
    description: "Identifies conflicting specifications (e.g. ultra-low budget for micron-level titanium 5-axis CNC).",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { budget: "number", material: "string", tolerance: "string" },
    outputSchema: { hasConflict: "boolean", conflictDetails: "string[]" },
    toolsRequired: ["engineering_rules_engine"],
  },
  quantity_estimation_calculator: {
    id: "quantity_estimation_calculator",
    name: "Batch Quantity & MOQ Estimator",
    category: "demand_capture",
    description: "Calculates optimal batch quantities based on machine setup costs and amortized tooling.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { targetBudget: "number", category: "string" },
    outputSchema: { recommendedBatch: "number", breakevenPoint: "number" },
    toolsRequired: ["cost_model_calculator"],
  },
  budget_timing_capture: {
    id: "budget_timing_capture",
    name: "Budget & Milestone Timing Extractor",
    category: "demand_capture",
    description: "Extracts milestone disbursement schedules and dispatch lead-time requirements.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { rawTimelineText: "string" },
    outputSchema: { advancePercent: "number", leadTimeDays: "number" },
    toolsRequired: ["gemini_generate_content"],
  },
  cad_drawing_parser: {
    id: "cad_drawing_parser",
    name: "CAD & Technical Drawing Analyzer",
    category: "demand_capture",
    description: "Extracts dimensions, GD&T symbols, and surface finishes from uploaded 2D/3D CAD blueprints.",
    status: "planned",
    isImplemented: false,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: true,
    inputSchema: { cadFileUri: "string" },
    outputSchema: { boundingDimensions: "string", surfaceFinish: "string" },
    toolsRequired: ["gemini_vision", "cad_vector_parser"],
  },

  // ─── 2. SUPPLIER DISCOVERY & MSME ENABLEMENT (11–20) ──────────────────────
  supplier_matching_engine: {
    id: "supplier_matching_engine",
    name: "Multi-Factor MSME Matching Engine",
    category: "supplier_discovery",
    description: "Matches requirements against verified factory profiles, machinery capacity, and past batch ratings.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { category: "string", budget: "number", location: "string?" },
    outputSchema: { matchedSuppliers: "object[]", matchScores: "number[]" },
    toolsRequired: ["msme_database", "vector_matching"],
  },
  match_explainer_engine: {
    id: "match_explainer_engine",
    name: "Match Transparency & Evidence Explainer",
    category: "supplier_discovery",
    description: "Generates clear, audit-ready explanations for why specific suppliers were prioritized.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "admin"],
    requiresHumanApproval: false,
    inputSchema: { supplierId: "string", rfqId: "string" },
    outputSchema: { evidenceFactors: "object[]", overallFit: "string" },
    toolsRequired: ["evidence_synthesizer"],
  },
  msme_profile_builder: {
    id: "msme_profile_builder",
    name: "MSME Factory Profile Builder",
    category: "supplier_discovery",
    description: "Extracts machinery rosters and capacity data from factory invoices and Udyam filings.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["msme"],
    requiresHumanApproval: true,
    inputSchema: { udyamCertText: "string", machineryList: "string[]" },
    outputSchema: { structuredProfile: "object", readinessScore: "number" },
    toolsRequired: ["gemini_generate_content"],
  },
  catalogue_enrichment_copilot: {
    id: "catalogue_enrichment_copilot",
    name: "Catalogue Enrichment Copilot",
    category: "supplier_discovery",
    description: "Enriches raw product listings with HSN codes, GST rates, and technical specifications.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["msme", "admin"],
    requiresHumanApproval: true,
    inputSchema: { rawTitle: "string", description: "string" },
    outputSchema: { hsnCode: "string", gstRate: "number", bulletPoints: "string[]" },
    toolsRequired: ["gemini_generate_content", "hsn_lookup"],
  },
  entity_resolution_detector: {
    id: "entity_resolution_detector",
    name: "MSME Entity Resolution & De-duplication",
    category: "supplier_discovery",
    description: "Detects duplicate factory registrations across PAN, GSTIN, and physical address records.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { gstin: "string", pan: "string", address: "string" },
    outputSchema: { isDuplicate: "boolean", matchedEntityId: "string?" },
    toolsRequired: ["entity_graph_auditor"],
  },
  statutory_verification_workflow: {
    id: "statutory_verification_workflow",
    name: "Statutory Verification & Udyam Audit",
    category: "supplier_discovery",
    description: "Verifies factory claims against live GSTIN and Ministry of MSME statutory filings.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { udyamNumber: "string", gstin: "string" },
    outputSchema: { isValid: "boolean", zedStatus: "string", verifiedDate: "string" },
    toolsRequired: ["gstin_validator", "udyam_verifier"],
  },
  capacity_lead_time_fit: {
    id: "capacity_lead_time_fit",
    name: "Machine Capacity & Slot Fit Analyzer",
    category: "supplier_discovery",
    description: "Cross-checks factory machine idle hours against required dispatch turnaround.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { targetDeliveryDays: "number", requiredMachineHours: "number" },
    outputSchema: { slotAvailable: "boolean", estimatedLeadDays: "number" },
    toolsRequired: ["machine_telemetry_ledger"],
  },
  cluster_coverage_gap_analyzer: {
    id: "cluster_coverage_gap_analyzer",
    name: "Regional Cluster Coverage Gap Analyzer",
    category: "supplier_discovery",
    description: "Identifies industrial clusters lacking verified capacity for emerging tech products.",
    status: "planned",
    isImplemented: false,
    confidenceSupported: false,
    requiredRole: ["admin"],
    requiresHumanApproval: false,
    inputSchema: { region: "string", category: "string" },
    outputSchema: { coverageRatio: "number", supplierCount: "number" },
    toolsRequired: ["geo_cluster_indexer"],
  },
  alternative_supplier_suggester: {
    id: "alternative_supplier_suggester",
    name: "Alternative Material & Supplier Suggester",
    category: "supplier_discovery",
    description: "Suggests alternative manufacturing processes when primary factory slots are fully booked.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { bottleneckMaterial: "string" },
    outputSchema: { substituteMaterials: "string[]", potentialSavings: "string" },
    toolsRequired: ["material_knowledge_base"],
  },
  msme_rfq_response_copilot: {
    id: "msme_rfq_response_copilot",
    name: "MSME Quote Drafting Copilot",
    category: "supplier_discovery",
    description: "Assists MSME floor managers in drafting structured, competitive bids with tooling breakdown.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["msme"],
    requiresHumanApproval: true,
    inputSchema: { rfqSpecs: "object", rawNotes: "string" },
    outputSchema: { unitRate: "number", toolingCharge: "number", technicalNotes: "string" },
    toolsRequired: ["gemini_generate_content"],
  },

  // ─── 3. RFQ, QUOTATION & COMMERCIAL COMPARISON (21–31) ────────────────────
  rfq_generation_engine: {
    id: "rfq_generation_engine",
    name: "Institutional RFQ Generation Engine",
    category: "rfq_quotation",
    description: "Produces standardized, legally binding RFQ documents from conversational requirements.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: true,
    inputSchema: { requirement: "object" },
    outputSchema: { rfqId: "string", rfqMarkdown: "string" },
    toolsRequired: ["rfq_builder"],
  },
  supplier_specific_rfq_customizer: {
    id: "supplier_specific_rfq_customizer",
    name: "Supplier-Specific RFQ Customizer",
    category: "rfq_quotation",
    description: "Adapts RFQ technical phrasing to match specific factory machine specifications.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { rfqData: "object", supplierMachinery: "string[]" },
    outputSchema: { tailoredNotes: "string" },
    toolsRequired: ["gemini_generate_content"],
  },
  supplier_question_triage: {
    id: "supplier_question_triage",
    name: "Supplier Inquiry Auto-Triage",
    category: "rfq_quotation",
    description: "Categorizes factory pre-bid inquiries into technical, commercial, or logistics questions.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { questionText: "string" },
    outputSchema: { category: "string", urgency: "string", draftedAnswer: "string?" },
    toolsRequired: ["gemini_generate_content"],
  },
  quote_document_extractor: {
    id: "quote_document_extractor",
    name: "Quotation Document & PDF Extractor",
    category: "rfq_quotation",
    description: "Extracts line items, taxes, freight, and terms from uploaded supplier PDF quotations.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: true,
    inputSchema: { documentText: "string" },
    outputSchema: { unitRate: "number", toolingCost: "number", gst: "number", lineItems: "object[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  quote_line_item_mapper: {
    id: "quote_line_item_mapper",
    name: "Line-Item Normalization & Mapping",
    category: "rfq_quotation",
    description: "Normalizes disparate vendor line-item terminologies into standard MPI cost ledgers.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { rawLineItems: "object[]" },
    outputSchema: { normalizedLedger: "object" },
    toolsRequired: ["normalization_rules"],
  },
  commercial_normalization_engine: {
    id: "commercial_normalization_engine",
    name: "Reverse-Margin Normalization Engine",
    category: "rfq_quotation",
    description: "Calculates total landed unit cost across GST input credits, freight, and tooling amortization.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { quotes: "object[]" },
    outputSchema: { normalizedQuotes: "object[]", savingsLeader: "string" },
    toolsRequired: ["financial_math_engine"],
  },
  like_for_like_comparator: {
    id: "like_for_like_comparator",
    name: "Like-for-Like Bid Comparator",
    category: "rfq_quotation",
    description: "Normalizes unequal vendor bids into uniform unit pricing with quality adjustments.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { quoteA: "object", quoteB: "object" },
    outputSchema: { varianceReport: "object", recommendation: "string" },
    toolsRequired: ["comparator_engine"],
  },
  quote_validity_monitor: {
    id: "quote_validity_monitor",
    name: "Quotation Validity & Raw Material Indexer",
    category: "rfq_quotation",
    description: "Tracks commodity index swings (aluminum, kraft paper) to alert on quote expiration.",
    status: "planned",
    isImplemented: false,
    confidenceSupported: false,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { quoteDate: "string", material: "string" },
    outputSchema: { isExpiring: "boolean", priceVolatilityWarning: "string?" },
    toolsRequired: ["commodity_ticker_feed"],
  },
  price_benchmark_engine: {
    id: "price_benchmark_engine",
    name: "National Industrial Price Benchmarking",
    category: "rfq_quotation",
    description: "Compares supplier quote against historical cluster averages to detect inflation.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "admin"],
    requiresHumanApproval: false,
    inputSchema: { itemCategory: "string", unitPrice: "number" },
    outputSchema: { clusterAverage: "number", percentDiff: "number", assessment: "string" },
    toolsRequired: ["mpi_historical_ledger"],
  },
  negotiation_guidance_copilot: {
    id: "negotiation_guidance_copilot",
    name: "Negotiation Preparation Copilot",
    category: "rfq_quotation",
    description: "Recommends targeted counter-proposals based on batch size scaling and payment term concessions.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: true,
    inputSchema: { currentQuote: "object", targetBudget: "number" },
    outputSchema: { recommendedCounter: "number", negotiationArguments: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  award_memo_generator: {
    id: "award_memo_generator",
    name: "Executive Procurement Award Memo Generator",
    category: "rfq_quotation",
    description: "Drafts comprehensive justification memo for executive audit and finance approval.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "admin"],
    requiresHumanApproval: true,
    inputSchema: { winningQuote: "object", rfqSummary: "object" },
    outputSchema: { memoMarkdown: "string", executiveSummary: "string" },
    toolsRequired: ["gemini_generate_content"],
  },

  // ─── 4. SCHEMES, COMPLIANCE & BUSINESS NAVIGATION (32–38) ────────────────
  scheme_matcher_engine: {
    id: "scheme_matcher_engine",
    name: "Government Scheme Matching Engine",
    category: "schemes_compliance",
    description: "Matches startup RFQs with 30+ central and state subsidies (ZED, SISFS, Design Clinic).",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { profile: "object", category: "string" },
    outputSchema: { matchedSchemes: "object[]", potentialGrantValue: "number" },
    toolsRequired: ["mpi_schemes_database"],
  },
  scheme_eligibility_screener: {
    id: "scheme_eligibility_screener",
    name: "Pre-Screen Eligibility Auditor",
    category: "schemes_compliance",
    description: "Runs statutory checklist to determine grant approval likelihood before filing.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { schemeCode: "string", companyData: "object" },
    outputSchema: { eligible: "boolean", score: "number", missingDocs: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  deadline_monitoring_assistant: {
    id: "deadline_monitoring_assistant",
    name: "Subsidy Filing Deadline Tracker",
    category: "schemes_compliance",
    description: "Tracks state and central fiscal grant window closures and sends timely submission alerts.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: false,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { activeSchemes: "string[]" },
    outputSchema: { upcomingDeadlines: "object[]" },
    toolsRequired: ["calendar_engine"],
  },
  application_checklist_generator: {
    id: "application_checklist_generator",
    name: "Grant Application Checklist Generator",
    category: "schemes_compliance",
    description: "Assembles exact documentary requirements for DPIIT seed funds and ZED fee exemptions.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { schemeId: "string" },
    outputSchema: { mandatoryChecklist: "string[]", optionalSupporting: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  compliance_calendar_builder: {
    id: "compliance_calendar_builder",
    name: "Statutory MSME Compliance Calendar",
    category: "schemes_compliance",
    description: "Builds unified calendar for GST return filings, factory inspectorate audits, and lab renewals.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: false,
    requiredRole: ["msme"],
    requiresHumanApproval: false,
    inputSchema: { enterpriseType: "string" },
    outputSchema: { monthlyFilings: "object[]" },
    toolsRequired: ["compliance_rules_engine"],
  },
  contract_summarizer: {
    id: "contract_summarizer",
    name: "Escrow Contract & SLA Summarizer",
    category: "schemes_compliance",
    description: "Summarizes indemnity, warranty, and drop-test milestone release conditions in plain language.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: true,
    inputSchema: { legalText: "string" },
    outputSchema: { plainSummary: "string", riskClauses: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  dispute_mediation_copilot: {
    id: "dispute_mediation_copilot",
    name: "Dispute Mediation & Escrow Arbitrator",
    category: "schemes_compliance",
    description: "Analyzes lab defect reports and bills of lading to recommend fair escrow holdback adjustments.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { disputeContext: "object" },
    outputSchema: { proposedResolution: "string", refundRatio: "number" },
    toolsRequired: ["gemini_generate_content"],
  },

  // ─── 5. ANALYTICS, FORECASTING, RISK & PERFORMANCE (39–50) ───────────────
  spend_analytics_engine: {
    id: "spend_analytics_engine",
    name: "Procurement Spend & Savings Studio",
    category: "analytics_forecasting",
    description: "Analyzes historical procurement spend across categories to isolate reverse-margin savings.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "admin"],
    requiresHumanApproval: false,
    inputSchema: { timeRange: "string" },
    outputSchema: { totalSpend: "number", realizedSavings: "number", categoryBreakdown: "object[]" },
    toolsRequired: ["analytics_aggregator"],
  },
  demand_forecasting_engine: {
    id: "demand_forecasting_engine",
    name: "Seasonal Demand & Reorder Forecaster",
    category: "analytics_forecasting",
    description: "Projects quarterly material demand spikes using regional retail seasonality curves.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { category: "string", historicalSales: "number[]" },
    outputSchema: { projectedUnits: "number", peakMonth: "string" },
    toolsRequired: ["gemini_generate_content"],
  },
  price_volatility_forecaster: {
    id: "price_volatility_forecaster",
    name: "Raw Material Price Volatility Forecaster",
    category: "analytics_forecasting",
    description: "Predicts upcoming price shifts in polymers, aluminum, and paperboard.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { material: "string" },
    outputSchema: { trendDirection: "string", expectedShiftPercent: "number" },
    toolsRequired: ["gemini_generate_content"],
  },
  msme_inventory_reorder_calculator: {
    id: "msme_inventory_reorder_calculator",
    name: "MSME Tooling & Inventory Reorder Planner",
    category: "analytics_forecasting",
    description: "Calculates optimal stock replenishment points based on vendor factory lead times.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["msme"],
    requiresHumanApproval: false,
    inputSchema: { currentStock: "number", burnRate: "number", leadDays: "number" },
    outputSchema: { reorderPoint: "number", safetyStock: "number" },
    toolsRequired: ["gemini_generate_content"],
  },
  lead_time_prediction_engine: {
    id: "lead_time_prediction_engine",
    name: "Factory Floor Lead-Time Predictor",
    category: "analytics_forecasting",
    description: "Estimates real-world dispatch dates factoring in industrial cluster power and logistics delays.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { supplierCluster: "string", quantity: "number" },
    outputSchema: { predictedDays: "number", confidenceInterval: "string" },
    toolsRequired: ["cluster_telemetry"],
  },
  supplier_performance_scorecard: {
    id: "supplier_performance_scorecard",
    name: "MSME Factory Performance Scorecard",
    category: "analytics_forecasting",
    description: "Computes weighted supplier rating based on drop-test pass rates and on-time fulfillment.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup", "admin"],
    requiresHumanApproval: false,
    inputSchema: { supplierId: "string" },
    outputSchema: { compositeScore: "number", defectRate: "number", onTimeRate: "number" },
    toolsRequired: ["metrics_aggregator"],
  },
  risk_anomaly_auditor: {
    id: "risk_anomaly_auditor",
    name: "Procurement Risk & Anomaly Auditor",
    category: "analytics_forecasting",
    description: "Scans RFQ and quotation logs for collusion patterns, inflated tooling, and phantom bidders.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { transactionData: "object" },
    outputSchema: { riskScore: "number", anomalyFlags: "string[]", isFlagged: "boolean" },
    toolsRequired: ["gemini_generate_content"],
  },
  duplicate_payment_detector: {
    id: "duplicate_payment_detector",
    name: "Escrow Duplicate Invoice & Payment Detector",
    category: "analytics_forecasting",
    description: "Flags duplicate GSTIN invoices or double-claimed escrow milestone advances.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { invoiceNumber: "string", amount: "number", supplierGstin: "string" },
    outputSchema: { isDuplicate: "boolean", previousPaymentId: "string?" },
    toolsRequired: ["escrow_audit_ledger"],
  },
  supplier_concentration_analyzer: {
    id: "supplier_concentration_analyzer",
    name: "Supply Chain Single-Source Concentration Analyzer",
    category: "analytics_forecasting",
    description: "Calculates single-source dependency risks and recommends backup tooling sources.",
    status: "planned",
    isImplemented: false,
    confidenceSupported: false,
    requiredRole: ["startup", "admin"],
    requiresHumanApproval: false,
    inputSchema: { spendHistory: "object[]" },
    outputSchema: { topVendorShare: "number", riskRating: "string" },
    toolsRequired: ["concentration_math"],
  },
  savings_measurement_ledger: {
    id: "savings_measurement_ledger",
    name: "Realized Reverse-Margin Savings Ledger",
    category: "analytics_forecasting",
    description: "Calculates verified cash savings against traditional offline distributor quotes.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { mpiPrice: "number", brokerBenchmark: "number" },
    outputSchema: { netSavingsRupees: "number", savingsPercentage: "number" },
    toolsRequired: ["cost_model_calculator"],
  },
  defect_rate_trend_tracker: {
    id: "defect_rate_trend_tracker",
    name: "Batch Quality Defect Rate Tracker",
    category: "analytics_forecasting",
    description: "Tracks dimensional variance trends across successive production batches.",
    status: "planned",
    isImplemented: false,
    confidenceSupported: false,
    requiredRole: ["startup", "admin"],
    requiresHumanApproval: false,
    inputSchema: { supplierId: "string" },
    outputSchema: { historicalDefectPpm: "number[]" },
    toolsRequired: ["qa_telemetry_db"],
  },
  logistics_carbon_estimator: {
    id: "logistics_carbon_estimator",
    name: "Industrial Corridor Logistics Carbon Estimator",
    category: "analytics_forecasting",
    description: "Estimates freight carbon footprint based on proximity to nearest regional MSME cluster.",
    status: "planned",
    isImplemented: false,
    confidenceSupported: false,
    requiredRole: ["startup"],
    requiresHumanApproval: false,
    inputSchema: { factoryPin: "string", destinationPin: "string", weightKg: "number" },
    outputSchema: { estimatedKgCo2: "number", nearestCorridor: "string" },
    toolsRequired: ["geo_distance_calculator"],
  },

  // ─── 6. COPILOTS, WORKFLOW & TRUST (51–62) ────────────────────────────────
  mpi_navigation_copilot: {
    id: "mpi_navigation_copilot",
    name: "MPI Conversational Procurement Copilot",
    category: "copilots_trust",
    description: "Multi-turn assistant helping startups navigate quotes, technical specifications, and subsidies.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup"],
    requiresHumanApproval: false,
    inputSchema: { userMessage: "string", history: "object[]" },
    outputSchema: { replyText: "string", suggestedActions: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  multilingual_voice_assistant: {
    id: "multilingual_voice_assistant",
    name: "Multilingual Voice & Vernacular Intake",
    category: "copilots_trust",
    description: "Supports voice procurement requests across Hindi, Tamil, Telugu, Marathi, and Kannada.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { audioTranscript: "string", languageCode: "string" },
    outputSchema: { translatedRequirement: "string", targetCategory: "string" },
    toolsRequired: ["gemini_generate_content"],
  },
  order_status_tracking_assistant: {
    id: "order_status_tracking_assistant",
    name: "Milestone SLA & Logistics Status Assistant",
    category: "copilots_trust",
    description: "Provides instant plain-language status updates on batch tooling, QA drop tests, and dispatches.",
    status: "available",
    isImplemented: true,
    confidenceSupported: false,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: false,
    inputSchema: { rfqId: "string" },
    outputSchema: { currentPhase: "string", nextGate: "string", eta: "string" },
    toolsRequired: ["order_state_machine"],
  },
  buyer_decision_support_engine: {
    id: "buyer_decision_support_engine",
    name: "Buyer Decision Support Recommendation Engine",
    category: "copilots_trust",
    description: "Ranks supplier bids across cost, lead time, and reliability without forcing automated selection.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["startup"],
    requiresHumanApproval: true,
    inputSchema: { bids: "object[]", buyerPriority: "string" },
    outputSchema: { rankedRecommendations: "object[]", tradeOffAnalysis: "string" },
    toolsRequired: ["gemini_generate_content"],
  },
  admin_platform_copilot: {
    id: "admin_platform_copilot",
    name: "Admin Governance & Telemetry Copilot",
    category: "copilots_trust",
    description: "Assists platform admins in auditing verifications, reviewing flags, and resolving disputes.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { adminQuery: "string", platformTelemetry: "object" },
    outputSchema: { analysis: "string", suggestedActions: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  model_fairness_monitor: {
    id: "model_fairness_monitor",
    name: "Model Fairness & Anti-Bias Telemetry Monitor",
    category: "copilots_trust",
    description: "Audits AI matching recommendations to ensure regional MSMEs receive equitable exposure.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: false,
    inputSchema: { recentMatches: "object[]" },
    outputSchema: { fairnessIndex: "number", clusterDistribution: "object", anomalies: "string[]" },
    toolsRequired: ["gemini_generate_content"],
  },
  live_auction_engine: {
    id: "live_auction_engine",
    name: "Live Reverse-Auction Orchestrator",
    category: "copilots_trust",
    description: "Orchestrates competitive timed bidding sessions for high-volume enterprise production batches.",
    status: "planned",
    isImplemented: false,
    confidenceSupported: false,
    requiredRole: ["startup", "msme"],
    requiresHumanApproval: true,
    inputSchema: { rfqId: "string", durationMinutes: "number" },
    outputSchema: { winningBidId: "string", totalRounds: "number" },
    toolsRequired: ["websocket_auction_room"],
  },
  contract_compliance_guardian: {
    id: "contract_compliance_guardian",
    name: "Contract Compliance & Escrow Gatekeeper",
    category: "copilots_trust",
    description: "Validates all condition precedents before escrow accounts trigger payment release.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { labPassProof: "string", dispatchDoc: "string" },
    outputSchema: { canDisburse: "boolean", verifiedConditions: "string[]" },
    toolsRequired: ["escrow_smart_gate"],
  },
  supplier_badge_recommender: {
    id: "supplier_badge_recommender",
    name: "Quality Tier & Verified Badge Recommender",
    category: "copilots_trust",
    description: "Evaluates consecutive zero-defect batches to promote MSMEs to Tier-1 Gold status.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin"],
    requiresHumanApproval: true,
    inputSchema: { supplierHistory: "object" },
    outputSchema: { recommendedTier: "string", qualificationReasons: "string[]" },
    toolsRequired: ["badge_rules_engine"],
  },
  data_privacy_redactor: {
    id: "data_privacy_redactor",
    name: "PII & Competitive Sourcing Redactor",
    category: "copilots_trust",
    description: "Strips proprietary founder contact details and CAD trade secrets from public RFQ teasers.",
    status: "available",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["public", "startup", "admin"],
    requiresHumanApproval: false,
    inputSchema: { rawRfqContent: "string" },
    outputSchema: { sanitizedContent: "string", redactedEntitiesCount: "number" },
    toolsRequired: ["regex_pii_sanitizer"],
  },
  automated_audit_log_generator: {
    id: "automated_audit_log_generator",
    name: "Statutory Audit Trail Generator",
    category: "copilots_trust",
    description: "Assembles immutable audit trails for bank escrow inspections and DPIIT grant acquittals.",
    status: "available",
    isImplemented: true,
    confidenceSupported: false,
    requiredRole: ["admin"],
    requiresHumanApproval: false,
    inputSchema: { rfqId: "string" },
    outputSchema: { auditTrailJson: "object", sha256Checksum: "string" },
    toolsRequired: ["audit_ledger_hasher"],
  },
  smart_contract_escrow_bridge: {
    id: "smart_contract_escrow_bridge",
    name: "Institutional Banking Escrow Bridge",
    category: "copilots_trust",
    description: "Cryptographically signs tripartite escrow agreements between buyer, supplier, and escrow agent.",
    status: "beta",
    isImplemented: true,
    confidenceSupported: true,
    requiredRole: ["admin", "startup"],
    requiresHumanApproval: true,
    inputSchema: { agreementId: "string", parties: "string[]" },
    outputSchema: { escrowAccountRef: "string", status: "string" },
    toolsRequired: ["banking_escrow_api"],
  },
}

/**
 * Capability Discovery Helpers
 */
export function getCapabilityById(id: string): AICapabilityDefinition | undefined {
  return MPI_AI_CAPABILITIES[id]
}

export function getCapabilitiesByCategory(category: AICapabilityCategory): AICapabilityDefinition[] {
  return Object.values(MPI_AI_CAPABILITIES).filter((cap) => cap.category === category)
}

export function getAvailableCapabilities(): AICapabilityDefinition[] {
  return Object.values(MPI_AI_CAPABILITIES).filter((cap) => cap.status === "available" || cap.status === "beta")
}

export function getPlannedRoadmapCapabilities(): AICapabilityDefinition[] {
  return Object.values(MPI_AI_CAPABILITIES).filter((cap) => cap.status === "planned")
}

/**
 * Standardized AI Output Factory (Section 5)
 */
export function createStandardAIOutput<T>(
  status: AIStandardOutput<T>["status"],
  result: T,
  confidenceScore: number,
  options: {
    missing_information?: string[]
    evidence?: AIEvidenceItem[]
    warnings?: string[]
    next_action?: AINextAction
  } = {},
): AIStandardOutput<T> {
  const score = Math.max(0, Math.min(1, confidenceScore))
  let level: AIConfidenceRating["level"] = "Insufficient evidence"
  if (score >= 0.8) {
    level = "High confidence"
  } else if (score >= 0.5) {
    level = "Needs confirmation"
  }

  return {
    status,
    result,
    confidence: {
      score,
      level,
    },
    missing_information: options.missing_information || [],
    evidence: options.evidence || [],
    warnings: options.warnings || [],
    next_action: options.next_action,
  }
}
